function [BW,maskedImage] = segmentSinglePlane(X)
%segmentImage Segment image using auto-generated code from imageSegmenter app
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the imageSegmenter app. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 22-Aug-2020
%----------------------------------------------------


% Normalize input data to range in [0,1].
Xmin = min(X(:));
Xmax = max(X(:));
if isequal(Xmax,Xmin)
    X = 0*X;
else
    X = (X - Xmin) ./ (Xmax - Xmin);
end

% define threshold with global contrast

ostu=graythresh(X);
addon=(0.15*(Xmax-Xmin)- Xmin) ./ (Xmax - Xmin);
% Threshold image - global threshold
BW = X > (ostu+addon);

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;
end

